#https://docs.python.org/2/distutils/index.html
#to find all available distribution formats:
#    $ python setup.py bdist --help-formats

#    Installer
#    ----------------------
#    To update installter files in ./dist/   ....
#      $ python2 setup.py bdist --formats=gztar,zip
#
#
#    MANIFEST & MANIFEST.in
#    ----------------------
#    MANIFEST is generated by Python.
#    MANIFEST.in is written by the Programmer (or generated by Python)
#
#    Everything in MANIFEST.in is done after the standard include set, so you 
#    can exclude files from the standard set with explicit instructions in the
#    manifest template. (Or, you can use the --no-defaults option to disable 
#    the standard set entirely.)
#
#    To regenerate MANIFEST (when structure inside ./eugene/{src,..} changes)
#      $ python2 setup.py sdist --manifest-only
#    
#    


from distutils.core import setup

#directory_created()
#file_created()


setup(name='eugene', 

      #version=1.0.0 = first version released on GitHub
      #format: major.minor[.patch][sub]
      version='0.1.1',

      author='Ben Jantzen',
      author_email='bjantzen@vt.edu',
      maintainer='Ben Jantzen',
      maintainer_email='bjantzen@vt.edu',
      url='http://www.ratiocination.org/',
      download_url='', #GitHub, eventually...
      description='AI for automated scientific discovery',
      long_description='',
      requires=['numpy', 'scipy'],
      #KIM: which versions are valid?
      classifiers=['Development Status :: 0 - Beta',
                   'Environment :: Console?',
                   'Intended Audience :: Developers & Scientists',
                   'License :: ...',
                   'Operating System :: Linux :: ArchLinux',
                   'Operating System :: Linux :: Debian Linux',
                   'Operating System :: Microsoft :: Windows',
                   'Programming Language :: Python',
                   'Topic :: AI - automated scientific discovery',],
      platforms='',
      license='',


      #specifying package as 'eugene' instead of root ('') installs
      #the package as a folder, rather than dumping the contents of that folder

      packages=['eugene', 'eugene.src', 
                'eugene.src.connect', 
                'eugene.src.virtual_sys',
                'eugene.tests',
                'eugene.scripts_demos']
#creates
#         site-packages/eugene/{src/, tests/}
#   and   site-packages/eugene-0.1.0-py2.7.egg-info/

)

